replicaCount: 1
# consulAgent.join: true
# consulAgent:
#   repository: consul
#   tag: 1.2.3
#   pullPolicy: IfNotPresent
  # HttpPort: 8500
ingress:
  enabled: true
  hosts:
    - vault.dev.anfa
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-production"
    certmanager.k8s.io/acme-challenge-type: "dns01"
    certmanager.k8s.io/acme-dns01-provider: "google-dns"
    kubernetes.io/ingress.class: "nginx-internal"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    - hosts:
        - vault.dev.anfa
      secretName: vault-tls
vault:
  # customSecrets:
  #   - secretName: gce-credentials
  #     mountPath: /gce
  dev: false
  extraEnv:
    - name: VAULT_API_ADDR
      value: "https://vault.dev.anfa"
    # - name: GOOGLE_APPLICATION_CREDENTIALS
    #   value: "/gce/gce_service_account.json"
  config:
    ui: true
    cluster_name: "sml"
    log_level: "debug"
    storage:
      file:
        path: "/mnt/vault/data"
      # gcs:
      #   bucket: "anfa-vault-backend"
      #   ha_enabled: "true"
      #   chunk_size: 1024
